account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user', views.EditUserView.as_view(), name='edit_user'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>', views.PostLikeView.as_view(), name='post_like')
]

social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account'))
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
from django.utils.text import slugify


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=50)
    body = models.TextField(max_length=1000)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated',)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Post, self).save()

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('home:post_detail', args=[self.id, self.slug])

    def likes_count(self):
        return self.pvotes.count()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:20]}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')

    def __str__(self):
        return f'{self.user} Liked {self.post.slug}'

home/forms.py
from django import forms
from .models import Post, Comment


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Type your comment here'})
        }
        labels = {
            "body": ""
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control ', 'rows': 3, 'placeholder': 'Type your reply here'})
        }
        labels = {
            "body": ""
        }


class PostSearchForm(forms.Form):
    search = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'special', 'placeholder': 'Search here'}))

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Post, Comment, Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostUpdateForm, PostCreateForm, CommentCreateForm, CommentReplyForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.


class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()

        if request.GET.get('search'):
            posts = posts.filter(title__icontains=request.GET.get('search'))
        return render(request, 'home/index.html', {'posts': posts, 'form': self.form_class})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, id=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(self, request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        return render(request, 'home/detail.html', {'post': self.post_instance, 'comments': comments,
                                                    'form': self.form_class, 'reply_form': self.form_class_reply})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'Your comment submitted successfully.', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'Post deleted successfully', 'success')
        else:
            messages.error(request, 'you can`t delete this post', 'danger')

        return redirect('home:home')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, 'you can not update this post', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, post_id):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'form': form})

    def post(self, request, post_id):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['title'])
            new_post.save()
            messages.success(request, 'You updated the post successfully', 'success')
            return redirect('home:post_detail', post.id, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateForm

    def get(self, request):
        form = self.form_class
        return render(request, 'home/create.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['title'])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'You created your new post successfully', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply submitted successfully', 'success')
        return redirect('home:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):

    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(user=request.user, post=post)
        if like.exists():
            like.delete()
            messages.error(request, 'You disliked this post', 'danger')
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, 'You liked this post successfully', 'success')
        return redirect('home:post_detail', post.id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}


<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create">

</form>


{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h4>{{ post.title }}</h4>
    <a href="{% url 'account:profile' post.user.id %}"><h6>{{ post.user.username }}</h6></a>
    <p>{{ post.body }}</p>
    <p>{{ post.updated|date:'Y-M' }}</p>

    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-primary">Update</a>
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
    <hr>
    <p>{{ comments.count }} Comments</p>
    {% if request.user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <a href="{% url 'home:post_like' post.id %}" class="btn btn-danger">{{ post.likes_count }} Likes</a>
                    <hr>
                    <div class="down-contact">
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Send" class="btn btn-primary mb-2">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p class="alert alert-danger">Please login to add comment.</p>
    {% endif %}
    {% for comment in comments %}
        <div class="card bg-dark text-white"><p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}
            ago </p>
            <P class="card-body">{{ comment.body }}</P>
            {% if request.user.is_authenticated %}
                <div class="container">
                <div class="row">
                <div class="col-lg-12">
                <div class="down-contact">
                <div class="row">

                    <div class="col-lg-4">
                        <form action="{% url 'home:add_reply' post.id comment.id %}" method="post">
                            {% csrf_token %}
                            {{ reply_form.as_p }}
                            <input type="submit" value="Send" class="btn btn-primary mb-2">
                        </form>
                    </div>
                </div>


            {% endif %}
            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <P class="bg-secondary p-4 m-3">{{ reply.user }} <br>{{ reply.body }}</p>

                {% endfor %}
                </div>
                </div>
                </div>
                </div>
                </div>
            {% endwith %}
        </div> <br>
    {% empty %}
        <p> No Comments yet </p>
    {% endfor %}

{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-center">Home page</h2>

    <form action="" method="get">
    {{ form }}
    <input type="submit" class="btn btn-dark" value="Search">

    </form>

    <div class="card">
    {% for post in posts %}
        <a class="card-body" href="{{ post.get_absolute_url }}" style="text-decoration: none" ><h6>{{ post.title }}</h6>
        {{ post.body|truncatewords:15 }}</a><hr>
    {% endfor %}
    </div>

{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Update">

</form>

{% endblock %}